spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/micro_service_sample
    username: root
    password: tgk1314lyh
  jpa:
    hibernate:
      ddl-auto: none

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5 # Do not do this in production

# HTTP Server
server:
  port: 2222 # HTTP (Tomcat) port

from: 58devops